<h2>Uber Rapsy - Terms of Service and Privacy Policy</h2>
<p class="ToSParagraph">1. This policy is the only written policy concerning user data privacy and terms of service of Uber Rapsy. It should always be kept up to date. If you have received information contrary to the policy, let us know immediately and we will verify it and update the policy accordingly.</p>
<p class="ToSParagraph">2. Use of Uber Rapsy is free. Nobody from our staff will ever contact you requesting money for access to our standard services. Please report such situations to us immediately. In case of subscribed users, billing may contact you in case of payment difficulties. You can escalate such situations for verification if you are unsure if they are genuine. Instructions on how to do this will be included in the original message. If they are not, the message is not from us.</p>
<p class="ToSParagraph">3. The only means of communication with staff is by using the form in your user panel. The form becomes accessible once the platform has reached the public release stage.</p>
<p class="ToSParagraph">4. Uber Rapsy may lock your account, delete any content generated by you, and forbid you access to its services at any time. In such cases, within 48 working hours, you will receive an email specifying the reason, further actions, and whether the penalty can be appealed.</p>
<p class="ToSParagraph">5. The Terms of Service (ToS) may change at any time. Users will receive prior notification in case of critical changes, giving them enough time to close their account in case of disagreement.</p>
<p class="ToSParagraph">6. We collect and store various types of user-provided and user-generated data. This data will never be sold or published outside of our own services. User account data will never leave this service.</p>
<p class="ToSParagraph">7. All of Uber Rapsy owners have access to your account data. This data will only be accessed when communicating with you on your request, or investigating a case under ToS point 3.</p>
<p class="ToSParagraph">8. Any data generated or provided by you (account data is not included) may be used to improve Uber Rapsy's functionality. You will not be notified of this.</p>
<p class="ToSParagraph">9. You may contact Uber Rapsy and ask to see or delete all of your data (the right to be forgotten). We will contact you regarding your request within 48 hours and complete the request within 30 working days. You can request this in your account settings.</p>
<p class="ToSParagraph">10. User-generated or user-provided data (ex. reviews, album-playlists, blog posts) that are factually correct and non-personal (ex. custom playlists, outside an album) may be claimed by Uber Rapsy to ensure service longevity and promotion. If the user then leaves the platform, any personally-identifying and account-identifying parts of the content will be anonymised for further use on the platform.</p>
<p class="ToSParagraph">11. Use of our basic services is FREE. Report to us any and all attempts of staff attempting to take any money from you for using the basic services. Billing may reach out to you in case of paid services (see ToS point 1).</p>
<br />

<div class="tos--button">
    <button role="button" class="btn btn-info tos--button" onclick="window.open('', '_self', ''); window.close();">Close</button>
</div><?php
